Repository angular/preboot, pull requests merged in 2018-02, with the labels that each got.

#71 feat: rename noReplay to replay; set to true by default
  README.md
  src/lib/api/event.recorder.ts
  src/lib/api/inline.preboot.code.ts
  src/lib/common/preboot.interfaces.ts
  src/lib/module.ts
Labels: pr: needs review

#70 test: enable autoWatch in karma.conf.js
  karma.conf.js
Labels: pr: needs review

#77 feat(module): only add the inline script if not in the DOM
  src/lib/api/inline.preboot.code.ts
  src/lib/module.ts
  src/lib/provider.ts
Labels: cla: yes, pr: needs review

#78 chore: cut the 6.0.0-beta.3 release
  package.json
  src/lib/package.json
Labels: cla: yes
